[editor]
show_white_space=false
show_indent_guide=true
show_line_endings=false
line_wrapping=false
auto_continue_multiline=true
smart_home_key=true
smart_tabbing=true
complete_snippets=true
strip_trailing_spaces=true
replace_tabs=true
ensure_convert_new_lines=true
pref_editor_newline=true
indent_type=1
indent_width=4
auto_indent=true
detect_indent=true
detect_indent_width=true
close_comments=true
autoclose_chars=([{'"`"
auto_close_xml_tags=false

[files]
default_open_path=/home/vincent/Documents/GitHub/dotS-language
use_safe_file_saving=true
check_detect_changes=true
disk_check_timeout=3000
cmdline_new_files=true

[tools]
terminal_cmd=env DOTS_CLI_STRICT=1 bash -lc "%c"

[build-menu]
save_all_before_build=true

[search]
use_regexp=true

[printing]
print_line_numbers=false

