# Geany filetype config for Vit command/runtime files
[styling=C]
lexer_filetype=CPP
comment_single=#

[keywords]
primary=space pull form proc const let give loop if else continue break entry at
secondary=true false null

[settings]
extension=vit
mime_type=text/plain
wordchars=abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_./-
comment_open=#
comment_close=
tag_parser=Regexp

[indentation]
width=4
type=1
hard_tabs=0
detect_indent=true
detect_indent_width=true

[build-settings]
compiler_regex=^(?:dots:\s*)?([^:]+):([0-9]+):?(.*)$

[tagmanager]
extension=vit
tm_parsers=Regex
regex_proc=^\s*proc\s+([A-Za-z0-9_]+)
regex_form=^\s*form\s+([A-Za-z0-9_]+)
